name: Testing first file

on:
  issues:
    types: [ opened, edited, closed ]

jobs:
  FirstJob:
    name: This is first job
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: This is first step
        run: echo "Hello, world! This is first step" 
    
  SecondJob:
    needs: FirstJob
    name: This is second job
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
        - name: This is second step
          run: echo "This is second step"
